import { ResourceProvider } from '../api/ConversationResource';
import { User } from '../model';
export declare const FETCH_CONVERSATIONS_REQUEST = "fetchConversationsRequest";
export declare const FETCH_CONVERSATIONS_SUCCESS = "fetchConversationsSuccess";
export declare const ADD_COMMENT_REQUEST = "addCommentRequest";
export declare const ADD_COMMENT_SUCCESS = "addCommentSuccess";
export declare const ADD_COMMENT_ERROR = "addCommentError";
export declare const DELETE_COMMENT_REQUEST = "deleteCommentRequest";
export declare const DELETE_COMMENT_SUCCESS = "deleteCommentSuccess";
export declare const DELETE_COMMENT_ERROR = "deleteCommentError";
export declare const UPDATE_COMMENT_REQUEST = "updateCommentRequest";
export declare const UPDATE_COMMENT_SUCCESS = "updateCommentSuccess";
export declare const UPDATE_COMMENT_ERROR = "updateCommentError";
export declare const HIGHLIGHT_COMMENT = "highlightComment";
export declare const REVERT_COMMENT = "revertComment";
export declare const UPDATE_USER_SUCCESS = "updateUserSuccess";
export declare const CREATE_CONVERSATION_REQUEST = "createConversationRequest";
export declare const CREATE_CONVERSATION_SUCCESS = "createConversationSuccess";
export declare const CREATE_CONVERSATION_ERROR = "createConversationError";
export declare type SuccessHandler = (id: string) => void;
export declare const addComment: (conversationId: string, parentId: string, value: any, localId: string | undefined, provider: ResourceProvider, onSuccess?: SuccessHandler | undefined) => () => Promise<void>;
export declare const updateComment: (conversationId: string, commentId: string, value: any, provider: ResourceProvider, onSuccess?: SuccessHandler | undefined) => () => Promise<void>;
export declare const deleteComment: (conversationId: string, commentId: string, provider: ResourceProvider, onSuccess?: SuccessHandler | undefined) => () => Promise<void>;
export declare const revertComment: (conversationId: string, commentId: string, provider: ResourceProvider) => () => Promise<void>;
export declare const updateUser: (user: User, provider: ResourceProvider) => () => Promise<void>;
export declare const createConversation: (localId: string, value: any, meta: any, provider: ResourceProvider, objectId: string, containerId?: string | undefined, onSuccess?: SuccessHandler | undefined) => () => Promise<void>;
export declare const saveDraft: (isLocal: boolean, value: any, conversationId: string, commentId: string | undefined, meta: any, provider: ResourceProvider, objectId: string, containerId?: string | undefined) => () => Promise<void>;
