/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Danish
export default {
  'fabric.atlassianSwitcher.switchTo': 'Skift til',
  'fabric.atlassianSwitcher.switchToTooltip': 'Skift til ...',
  'fabric.atlassianSwitcher.recent': 'Seneste',
  'fabric.atlassianSwitcher.more': 'Mere',
  'fabric.atlassianSwitcher.try': 'Prøv',
  'fabric.atlassianSwitcher.manageList': 'Administrér liste',
  'fabric.atlassianSwitcher.jiraProject': 'Jira-projekt',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence-område',
  'fabric.atlassianSwitcher.people': 'Personer',
  'fabric.atlassianSwitcher.administration': 'Administration',
  'fabric.atlassianSwitcher.discoverMore': 'Se flere',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
