/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// German
export default {
  'fabric.atlassianSwitcher.switchTo': 'Switch to',
  'fabric.atlassianSwitcher.switchToTooltip': 'Switch to …',
  'fabric.atlassianSwitcher.recent': 'Recent',
  'fabric.atlassianSwitcher.more': 'More',
  'fabric.atlassianSwitcher.try': 'Try',
  'fabric.atlassianSwitcher.manageList': 'Manage list',
  'fabric.atlassianSwitcher.jiraProject': 'Jira project',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence space',
  'fabric.atlassianSwitcher.people': 'People',
  'fabric.atlassianSwitcher.administration': 'Administration',
  'fabric.atlassianSwitcher.discoverMore': 'Discover more',
};
