/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// German
export default {
  'fabric.atlassianSwitcher.switchTo': 'Wechseln zu',
  'fabric.atlassianSwitcher.switchToTooltip': 'Wechseln zu …',
  'fabric.atlassianSwitcher.recent': 'Letzte',
  'fabric.atlassianSwitcher.more': 'Mehr',
  'fabric.atlassianSwitcher.try': 'Ausprobieren',
  'fabric.atlassianSwitcher.manageList': 'Liste verwalten',
  'fabric.atlassianSwitcher.jiraProject': 'Jira-Projekt',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence-Bereich',
  'fabric.atlassianSwitcher.people': 'Personen',
  'fabric.atlassianSwitcher.administration': 'Administration',
  'fabric.atlassianSwitcher.discoverMore': 'Mehr entdecken',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
