/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Spanish
export default {
  'fabric.atlassianSwitcher.switchTo': 'Cambiar a',
  'fabric.atlassianSwitcher.switchToTooltip': 'Cambiar a…',
  'fabric.atlassianSwitcher.recent': 'Recientes',
  'fabric.atlassianSwitcher.more': 'Más',
  'fabric.atlassianSwitcher.try': 'Pruébalo',
  'fabric.atlassianSwitcher.manageList': 'Administrar lista',
  'fabric.atlassianSwitcher.jiraProject': 'Proyecto Jira',
  'fabric.atlassianSwitcher.confluenceSpace': 'Espacio de Confluence',
  'fabric.atlassianSwitcher.people': 'Personas',
  'fabric.atlassianSwitcher.administration': 'Administración',
  'fabric.atlassianSwitcher.discoverMore': 'Descubrir más',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
