/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Estonian
export default {
  'fabric.atlassianSwitcher.switchTo': 'Asenda tootega',
  'fabric.atlassianSwitcher.switchToTooltip': 'Asenda tootega …',
  'fabric.atlassianSwitcher.recent': 'Hiljutised',
  'fabric.atlassianSwitcher.more': 'Rohkem',
  'fabric.atlassianSwitcher.try': 'Proovi',
  'fabric.atlassianSwitcher.manageList': 'Halda loendit',
  'fabric.atlassianSwitcher.jiraProject': 'Jira projekt',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence’i ruum',
  'fabric.atlassianSwitcher.people': 'Inimesed',
  'fabric.atlassianSwitcher.administration': 'Administreerimine',
  'fabric.atlassianSwitcher.discoverMore': 'Avasta veel',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
