/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Finnish
export default {
  'fabric.atlassianSwitcher.switchTo': 'Vaihda kohteeseen',
  'fabric.atlassianSwitcher.switchToTooltip': 'Vaihda kohteeseen …',
  'fabric.atlassianSwitcher.recent': 'Viimeaikainen',
  'fabric.atlassianSwitcher.more': 'Lisää',
  'fabric.atlassianSwitcher.try': 'Yritä',
  'fabric.atlassianSwitcher.manageList': 'Hallinnoi luetteloa',
  'fabric.atlassianSwitcher.jiraProject': 'Jira-projekti',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence-työtila',
  'fabric.atlassianSwitcher.people': 'Henkilöt',
  'fabric.atlassianSwitcher.administration': 'Hallinto',
  'fabric.atlassianSwitcher.discoverMore': 'Löydä enemmän',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
