/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// French
export default {
  'fabric.atlassianSwitcher.switchTo': 'Passer à',
  'fabric.atlassianSwitcher.switchToTooltip': 'Passer à…',
  'fabric.atlassianSwitcher.recent': 'Récents',
  'fabric.atlassianSwitcher.more': 'Plus',
  'fabric.atlassianSwitcher.try': 'Essayer',
  'fabric.atlassianSwitcher.manageList': 'Gérer la liste',
  'fabric.atlassianSwitcher.jiraProject': 'Projet Jira',
  'fabric.atlassianSwitcher.confluenceSpace': 'Espace Confluence',
  'fabric.atlassianSwitcher.people': 'Personnes',
  'fabric.atlassianSwitcher.administration': 'Administration',
  'fabric.atlassianSwitcher.discoverMore': "Découvrir d'autres produits",
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
