/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Hungarian
export default {
  'fabric.atlassianSwitcher.switchTo': 'Átváltás erre:',
  'fabric.atlassianSwitcher.switchToTooltip': 'Átváltás erre...',
  'fabric.atlassianSwitcher.recent': 'Legutóbbi',
  'fabric.atlassianSwitcher.more': 'Továbbiak',
  'fabric.atlassianSwitcher.try': 'Próbálja ki',
  'fabric.atlassianSwitcher.manageList': 'Lista kezelése',
  'fabric.atlassianSwitcher.jiraProject': 'Jira projekt',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence-munkatér',
  'fabric.atlassianSwitcher.people': 'Személyek',
  'fabric.atlassianSwitcher.administration': 'Adminisztráció',
  'fabric.atlassianSwitcher.discoverMore': 'Továbbiak felfedezése',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
