/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Icelandic
export default {
  'fabric.atlassianSwitcher.switchTo': 'Skipta í',
  'fabric.atlassianSwitcher.switchToTooltip': 'Skipta í ...',
  'fabric.atlassianSwitcher.recent': 'Nýlegt',
  'fabric.atlassianSwitcher.more': 'Meira',
  'fabric.atlassianSwitcher.try': 'Prófa',
  'fabric.atlassianSwitcher.manageList': 'Vinna með lista',
  'fabric.atlassianSwitcher.jiraProject': 'Jira-verkefni',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence-svæði',
  'fabric.atlassianSwitcher.people': 'Fólk',
  'fabric.atlassianSwitcher.administration': 'Stjórnun',
  'fabric.atlassianSwitcher.discoverMore': 'Uppgötva fleiri',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
