/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Italian
export default {
  'fabric.atlassianSwitcher.switchTo': 'Passa a',
  'fabric.atlassianSwitcher.switchToTooltip': 'Passa a...',
  'fabric.atlassianSwitcher.recent': 'Recenti',
  'fabric.atlassianSwitcher.more': 'Altri',
  'fabric.atlassianSwitcher.try': 'Prova',
  'fabric.atlassianSwitcher.manageList': 'Gestisci elenco',
  'fabric.atlassianSwitcher.jiraProject': 'Progetto Jira',
  'fabric.atlassianSwitcher.confluenceSpace': 'Spazio Confluence',
  'fabric.atlassianSwitcher.people': 'Persone',
  'fabric.atlassianSwitcher.administration': 'Amministrazione',
  'fabric.atlassianSwitcher.discoverMore': 'Scopri altri prodotti',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
