/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Japanese
export default {
  'fabric.atlassianSwitcher.switchTo': '切り替え',
  'fabric.atlassianSwitcher.switchToTooltip': '製品を切り替え...',
  'fabric.atlassianSwitcher.recent': '最近',
  'fabric.atlassianSwitcher.more': 'その他',
  'fabric.atlassianSwitcher.try': '試してみる',
  'fabric.atlassianSwitcher.manageList': 'リストの管理',
  'fabric.atlassianSwitcher.jiraProject': 'Jira プロジェクト',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence スペース',
  'fabric.atlassianSwitcher.people': 'ユーザー',
  'fabric.atlassianSwitcher.administration': '管理',
  'fabric.atlassianSwitcher.discoverMore': 'もっと見る',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
