/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Norwegian Bokmål
export default {
  'fabric.atlassianSwitcher.switchTo': 'Bytt til',
  'fabric.atlassianSwitcher.switchToTooltip': 'Bytt til …',
  'fabric.atlassianSwitcher.recent': 'Nylige',
  'fabric.atlassianSwitcher.more': 'Mer',
  'fabric.atlassianSwitcher.try': 'Prøv',
  'fabric.atlassianSwitcher.manageList': 'Administrer liste',
  'fabric.atlassianSwitcher.jiraProject': 'Jira-prosjekt',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence-område',
  'fabric.atlassianSwitcher.people': 'Personer',
  'fabric.atlassianSwitcher.administration': 'Administrasjon',
  'fabric.atlassianSwitcher.discoverMore': 'Få mer informasjon',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
