/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Dutch
export default {
  'fabric.atlassianSwitcher.switchTo': 'Overschakelen naar',
  'fabric.atlassianSwitcher.switchToTooltip': 'Overschakelen naar...',
  'fabric.atlassianSwitcher.recent': 'Recent',
  'fabric.atlassianSwitcher.more': 'Meer',
  'fabric.atlassianSwitcher.try': 'Uitproberen',
  'fabric.atlassianSwitcher.manageList': 'Lijst beheren',
  'fabric.atlassianSwitcher.jiraProject': 'Jira-project',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence-space',
  'fabric.atlassianSwitcher.people': 'Gebruikers',
  'fabric.atlassianSwitcher.administration': 'Beheer',
  'fabric.atlassianSwitcher.discoverMore': 'Meer ontdekken',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
