/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Polish
export default {
  'fabric.atlassianSwitcher.switchTo': 'Przełącz na',
  'fabric.atlassianSwitcher.switchToTooltip': 'Przełącz na…',
  'fabric.atlassianSwitcher.recent': 'Ostatnie',
  'fabric.atlassianSwitcher.more': 'Więcej',
  'fabric.atlassianSwitcher.try': 'Wypróbuj',
  'fabric.atlassianSwitcher.manageList': 'Zarządzaj listą',
  'fabric.atlassianSwitcher.jiraProject': 'Projekt Jira',
  'fabric.atlassianSwitcher.confluenceSpace': 'Przestrzeń Confluence',
  'fabric.atlassianSwitcher.people': 'Użytkownicy',
  'fabric.atlassianSwitcher.administration': 'Administracja',
  'fabric.atlassianSwitcher.discoverMore': 'Odkryj więcej',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
