/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Portuguese (Brazil)
export default {
  'fabric.atlassianSwitcher.switchTo': 'Alternar para',
  'fabric.atlassianSwitcher.switchToTooltip': 'Alternar para...',
  'fabric.atlassianSwitcher.recent': 'Recentes',
  'fabric.atlassianSwitcher.more': 'Mais',
  'fabric.atlassianSwitcher.try': 'Testar',
  'fabric.atlassianSwitcher.manageList': 'Gerenciar lista',
  'fabric.atlassianSwitcher.jiraProject': 'Projeto do Jira',
  'fabric.atlassianSwitcher.confluenceSpace': 'Espaço do Confluence',
  'fabric.atlassianSwitcher.people': 'Pessoas',
  'fabric.atlassianSwitcher.administration': 'Administração',
  'fabric.atlassianSwitcher.discoverMore': 'Descobrir mais',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
