/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Romanian
export default {
  'fabric.atlassianSwitcher.switchTo': 'Comutați la',
  'fabric.atlassianSwitcher.switchToTooltip': 'Comutați la…',
  'fabric.atlassianSwitcher.recent': 'Recente',
  'fabric.atlassianSwitcher.more': 'Mai mult',
  'fabric.atlassianSwitcher.try': 'Încercați',
  'fabric.atlassianSwitcher.manageList': 'Gestionați lista',
  'fabric.atlassianSwitcher.jiraProject': 'Proiect Jira',
  'fabric.atlassianSwitcher.confluenceSpace': 'Spațiu Confluence',
  'fabric.atlassianSwitcher.people': 'Persoane',
  'fabric.atlassianSwitcher.administration': 'Administrare',
  'fabric.atlassianSwitcher.discoverMore': 'Descoperiți mai multe',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
