/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Chinese
export default {
  'fabric.atlassianSwitcher.switchTo': '切换到',
  'fabric.atlassianSwitcher.switchToTooltip': '切换到 …',
  'fabric.atlassianSwitcher.recent': '最近',
  'fabric.atlassianSwitcher.more': '更多',
  'fabric.atlassianSwitcher.try': '尝试',
  'fabric.atlassianSwitcher.manageList': '管理列表',
  'fabric.atlassianSwitcher.jiraProject': 'Jira 项目',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence 空间',
  'fabric.atlassianSwitcher.people': '人员',
  'fabric.atlassianSwitcher.administration': '管理',
  'fabric.atlassianSwitcher.discoverMore': '发现更多',
  'fabric.atlassianSwitcher.errorHeading': 'Something went wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
};
