image: node:8.4.0
pipelines:
  branches:
    master:
      - step:
          script:
            - yarn global add pyarn
            - export PATH=$HOME/.yarn/bin:$PATH
            - pyarn install
            - yarn build
            - yarn test
  default:
    - step:
        script:
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.23.2
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn global add pyarn
          - pyarn install
          - yarn build
          - yarn lint
          - yarn test
