# Note: This image can be found in build/pipelines/docker-image
image: atlassianlabs/atlaskit-mk-2:1.0.8
# This ensures we do a full clone on each build which prevents issues when cross referencing
# changesets and releases
clone:
  depth: full
options:
  size: 2x

pipelines:
  branches:
    master:
      - step:
          script:
            # Note: in master, this script will rebase you onto latest origin/master.
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - (cd build/ci-scripts && yarn stop-if-older-build)
            - yarn build
            - node build/ci-scripts/run.if.package.changed.js @atlaskit/editor-mobile-bridge -- yarn build:editor-mobile-bridge
            # Bump all packages and their dependents using saved changesets.
            - node ./build/releases/bin/build-releases.js version
            # We push the bumped packages to master now as it's much better to fail whilst BB is
            # ahead of npm, than the other way round.
            - git push
            # We run the build:pkg script again, because the versions in our package.jsons may have changed
            # after the bump. We've kept it running in both places, just to limit the scope of this change
            # so that we don't break anything that was working previously.
            - yarn build:pkg
            # Release all unreleased packages.
            - node ./build/releases/bin/build-releases.js publish --public
            - git push --tags # Push only the tags.
            - (cd build/ci-scripts && yarn restart-stopped-build)
          caches:
            - node

  default:
    - parallel:
        - step:
            name: Building dists
            script:
              - source ./build-setup.sh
              - bolt install --pure-lockfile
              - yarn build
              - node build/ci-scripts/run.if.package.changed.js @atlaskit/editor-mobile-bridge -- yarn build:editor-mobile-bridge
            caches:
              - node
        - step:
            name: Lint + Typecheck
            script:
              - source ./build-setup.sh
              - bolt install --pure-lockfile
              - node build/ci-scripts/run.tool.if.changed.js eslint -- yarn lint:eslint
              - node build/ci-scripts/run.tool.if.changed.js tslint -- yarn lint:tslint
              - node build/ci-scripts/run.tool.if.changed.js stylelint -- yarn lint:stylelint
              - node build/ci-scripts/run.tool.if.changed.js flow -- yarn typecheck:flow
              - node build/ci-scripts/run.tool.if.changed.js typescript -- yarn typecheck:typescript
              # Get the commit that we diverged from master at.
              - export DIVERGED_AT=$(git merge-base master HEAD)
              # Get a comma separated list of changed files.
              - export CHANGED_FILES=$(git diff --name-only $DIVERGED_AT -- 'packages' 'build' 'website' | grep -E 'js$|ts$|tsx$' | tr '\n' ',')
              # The below runs prettier over all changed files and fails if anyone of them don't match prettier's rules.
              # We add fileMock.js to the list of files so that we never pass an empty list to prettier.
              - yarn prettier --no-editorconfig "{$CHANGED_FILES,fileMock.js}" --list-different
            caches:
              - node
        - step:
            name: Check bundle sizes
            script:
              - source ./build-setup.sh
              - bolt install --pure-lockfile
              - bolt measure:changed
            caches:
              - node
        - step:
            name: Unit Testing
            script:
              - source ./build-setup.sh
              - bolt install --pure-lockfile
              # Run the non-editor tests, --passWithNoTests has been added in case of no tests found to avoid failure in CI.
              - TEST_ONLY_PATTERN='!packages/editor' yarn test:changed --passWithNoTests
              # Run the editor tests (runInBand is required or it fails in CI)
              - TEST_ONLY_PATTERN='packages/editor' yarn test:changed --runInBand --passWithNoTests
              # This script acts like a unit test to check changes to @atlaskit/adf-schema.
              - node build/ci-scripts/run.if.package.changed.js @atlaskit/adf-schema -- yarn build:adf-schema:checkuptodate
            caches:
              - node
        - step:
            name: Browser Unit Testing
            script:
              - source ./build-setup.sh
              - bolt install --pure-lockfile
              - echo "Run browser unit tests using Karma + Browserstack"
              - node build/ci-scripts/run.tool.if.changed.js karma -- yarn test:browser:browserstack
            caches:
              - node
        - step:
            name: Browser Integration Testing
            script:
              - source ./build-setup.sh
              - bolt install --pure-lockfile
              - echo "Run browser integration tests using Webdriver + Browserstack"
              # If we have changed any packages with webdriver tests, we wait until browserstack has free resources, then run our tests
              - LOCAL_IDENTIFIER=$(date +%s) BS_RETRY=5 BS_BUILD_ALLOWED=3 node build/ci-scripts/run.tool.if.changed.js webdriver -- node build/ci-scripts/wait.for.browserstack.resources.js && yarn test:webdriver:browserstack:changed
            caches:
              - node
        - step:
            name: Visual Regression Tests
            image: atlassianlabs/atlaskit-mk-2-vr:1.0.8
            script:
              - source ./build-setup.sh
              - git lfs pull
              - bolt install --pure-lockfile
              - yarn run test:vr:changed
            after-script:
              # Extract all the diff images and store them into a folder for download.
              - mkdir ./imageSnapshotFailures && find . -name '*-diff.png' -not -path "./node_modules/*" -exec cp {} ./imageSnapshotFailures \;
            # If a failure occurs, you can download the image snapshot of the differences.
            artifacts: 
              - imageSnapshotFailures/**
            caches:
              - node
        - step:
            name: Building website
            script:
              - source ./build-setup.sh
              - bolt install --pure-lockfile
              - cd website
              # This next line just makes it so we can skip website builds by having a branch name that starts with "skip-website/".
              - if [[ "$BITBUCKET_BRANCH" == skip-website/* ]]; then echo "Skipping website build" && mkdir dist && echo "Build skipped" > dist/index.html; else WEBSITE_ENV=staging yarn build:no-minimize; fi
              - yarn build:copy
              - set -o pipefail # Make sure we fail if the deployment fails.
              # We pipe the output to stdout AND deploy-log.txt so that we can read the live url
              - yarn deploy:staging | tee deploy-log.txt
              - cat deploy-log.txt | grep "URL:" | sed "s/Live Draft Url..//gi" > netlify-link.txt
              - echo "Uploading netlify build link to s3 so that we can fetch at the end..."
              - node ../build/ci-scripts/upload.build.artefact.for.commit.js netlify-link.txt
            caches:
              - node
    - step:
        name: Sending Website Build Url
        script:
          - (cd build/utils && yarn install) # Needed for npm-run when updating status.
          - cd build/ci-scripts
          - yarn install
          - node download.build.artefact.for.commit.js netlify-link.txt
          - node update.build.status.with.netlify.link.js

  # Pipelines that can be scheduled or triggered manually.
  custom: 
    # This should only be called by a scheduled build to deploy production website from latest master.
    build-website-production:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - cd website
            - WEBSITE_ENV=production yarn build
            - yarn build:copy
            - yarn deploy:production
          caches:
            - node

    # This can be called to deploy staging website from any branches.
    build-website-staging:
      - step:
          name: Building website
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - cd website
            - WEBSITE_ENV=staging yarn build:no-minimize
            - yarn build:copy
            - set -o pipefail
            - yarn deploy:staging | tee deploy-log.txt
            - cat deploy-log.txt | grep "URL:" | sed "s/Live Draft Url..//gi" > netlify-link.txt
            - echo "Uploading netlify build link to s3 so that we can fetch at the end..."
            - node ../build/ci-scripts/upload.build.artefact.for.commit.js netlify-link.txt
          caches:
            - node

    # This should only be called by a scheduled or manual build from master.
    # It builds the website and send the data to redash.
    send-website-build-analytics:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - cd website
            - yarn build:report
            # We could optionally upload these to s3 if we wanted, leaving this here as an example:
            # - node ../build/ci-scripts/upload.build.artefact.for.commit.js dist/report.html
            # - node ../build/ci-scripts/upload.build.artefact.for.commit.js dist/stats.json
            - node ./scripts/uploadBundleAnalyticsEvent.js
          caches:
            - node
   
    # This will run the full suite of the webdriver tests on Browserstack.
    build-webdriver:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - yarn test:webdriver:browserstack
          caches:
            - node
            
    # This will run the full suite of the visual regression tests using Docker.
    build-visual-regression:
      - step:
          image: atlassianlabs/atlaskit-mk-2-vr:1.0.8
          script:
            - source ./build-setup.sh
            - git lfs pull
            - bolt install --pure-lockfile
            - yarn run test:vr
          after-script:
              # Extract all the diff images and store them into a folder for download.
              - mkdir ./imageSnapshotFailures && find . -name '*-diff.png' -not -path "./node_modules/*" -exec cp {} ./imageSnapshotFailures \;
          # If a failure occurs, you can download the image snapshot of the differences.
          artifacts: 
            - imageSnapshotFailures/**
          caches:
            - node 
            
    # This will run essentially the branch builds, but without any optimizations and should be manually.
    # This build should be run in any potentially risky builds.
    run-full-suite:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - yarn build
            - yarn lint
            - yarn typecheck
            - yarn test:CI
            - yarn test:browser:browserstack
            - yarn test:webdriver:browserstack
            - yarn test:vr
            - cd website
            # don't worry about deploying, this build will always be run alongside a branch build
            - yarn build

    # This will build all the packages and run bundle-analysis.
    run-bundle-analysis:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - yarn build
            - yarn build:bundle-analysis
          caches:
            - node
    # This build is used as our `merge` build when managing concurrent PR to master.
    landkid:
      - parallel:
          - step:
              name: Building
              script:
                - source ./build-setup.sh
                - git merge master --no-edit
                - bolt install --pure-lockfile
                - yarn build

          - step:
              name: Linting
              script:
                - source ./build-setup.sh
                - git merge master --no-edit
                - bolt install --pure-lockfile
                - yarn lint

          - step:
              name: Typechecking (and checking changesets)
              script:
                - source ./build-setup.sh
                - git merge master --no-edit
                - bolt install --pure-lockfile
                - yarn typecheck
                - echo "We are now about to run the `version` command which will read changesets and bump packages"
                - echo "We do this so that we know if the repo will be in an inconsistent state when this branch hits master"
                - echo "If the step below fails, it's because a changeset may be bumping a package that is depended upon by a package that didn't exist when the changeset was created"
                - echo "Read the very last error message, it will tell you exactly what is wrong (ignore all the first warnings you'll see)"
                - node ./build/releases/bin/build-releases.js version
          # Rest of the steps are jest tests. We no longer use the $BITBUCKET_PARALLEL_STEP_COUNT and $BITBUCKET_PARALLEL_STEP
          # variables as they mean the jest steps need to be in their own parallel block, so we just hardcode them here.
          - step:
              name: Running Jest 1 of 4 chunks
              script:
                - source ./build-setup.sh
                - git merge master --no-edit
                - bolt install --pure-lockfile
                - export TMPFILE=$(mktemp /tmp/jest.XXXXXX) && yarn --silent jest --listTests --json > $TMPFILE
                - STEPS="4" STEP_IDX="0" PARALLELIZE_TESTS_FILE="$TMPFILE" yarn jest --runInBand
          - step:
              name: Running Jest 2 of 4 chunks
              script:
                - source ./build-setup.sh
                - git merge master --no-edit
                - bolt install --pure-lockfile
                - export TMPFILE=$(mktemp /tmp/jest.XXXXXX) && yarn --silent jest --listTests --json > $TMPFILE
                - STEPS="4" STEP_IDX="1" PARALLELIZE_TESTS_FILE="$TMPFILE" yarn jest --runInBand
          - step:
              name: Running Jest 3 of 4 chunks
              script:
                - source ./build-setup.sh
                - git merge master --no-edit
                - bolt install --pure-lockfile
                - export TMPFILE=$(mktemp /tmp/jest.XXXXXX) && yarn --silent jest --listTests --json > $TMPFILE
                - STEPS="4" STEP_IDX="2" PARALLELIZE_TESTS_FILE="$TMPFILE" yarn jest --runInBand
          - step:
              name: Running Jest 4 of 4 chunks
              script:
                - source ./build-setup.sh
                - git merge master --no-edit
                - bolt install --pure-lockfile
                - export TMPFILE=$(mktemp /tmp/jest.XXXXXX) && yarn --silent jest --listTests --json > $TMPFILE
                - STEPS="4" STEP_IDX="3" PARALLELIZE_TESTS_FILE="$TMPFILE" yarn jest --runInBand
          - step:
              name: Running Browser Integration tests
              script:
                - source ./build-setup.sh
                - git merge master --no-edit
                - bolt install --pure-lockfile
                - LANDKID=true yarn test:webdriver:browserstack:changed
          - step:
              name: Running Visual Regression tests
              image: atlassianlabs/atlaskit-mk-2-vr:1.0.8
              script:
                - source ./build-setup.sh
                - git merge master --no-edit
                - git lfs pull
                - bolt install --pure-lockfile
                - yarn test:vr:dependents
              after-script:
                # Extract all the diff images and store them into a folder for download.
                - mkdir ./imageSnapshotFailures && find . -name '*-diff.png' -not -path "./node_modules/*" -exec cp {} ./imageSnapshotFailures \;
              # If a failure occurs, you can download the image snapshot of the differences.
              artifacts: 
                - imageSnapshotFailures/**
      - step:
          name: Wait until no master is running
          script:
            - source ./build-setup.sh
            - cd build/ci-scripts
            - yarn --ignore-engines
            - node ./wait.until.no.master.build.running.js
    # This build should only be run on the master branch, once per day.
    # It manually clears the cache and runs a very quick install node_modules.
    # We split into two steps so that one can clear the cache so that the second one starts with no cache.
    # (Which causes it to upload when it's finished).
    reseed-pipelines-cache:
      - step:
          name: Clearing old cache
          script:
            - ([[ "$BITBUCKET_BRANCH" == "master" ]]) || (echo "This build should only be run on master" && exit 1)
            - cd build/ci-scripts
            - yarn install --pure-lockfile
            - node clear.pipelines.node.cache.js
      - step:
          name: Creating new cache
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            # We re-clear the cache here in case any other builds have managed to start and finish in between us starting.
            # (our build will only upload a cache if there is none when the build finishes).
            - node build/ci-scripts/clear.pipelines.node.cache.js
          caches:
            - node

    # This build allow to deploy branch dists to easily tests new version of components into consumers / products code base.
    deploy-branch-build-dists:
      - step:
          name: Deploy branch build dists
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - yarn build
            - export CHANGED_PACKAGES=$(node build/ci-scripts/get.changed.packages.since.master.js)
            # Change into a glob pattern (removing brackets, spaces and quotes).
            - export CHANGED_PACKAGES_GLOB=$(echo "$CHANGED_PACKAGES" | sed 's/[][" ]//g')
            # We add in the exta brances and a trailing comma in case we only have one package
            - bolt ws exec --only-fs="{$CHANGED_PACKAGES_GLOB,}" -- npm pack
            - mkdir -p dists/
            - node build/ci-scripts/copy.built.tgzs.to.dists.dir.js
            - for file in dists/*; do node build/ci-scripts/upload.build.artefact.for.commit.js $file dists/; done
          caches:
            - node
