image: node:8.4.0
pipelines:
  branches:
    master:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install
            - bolt build
            - bolt lint
            - bolt typecheck
            - bolt test
            - bolt test:browser:browserstack
            - bolt release
            # we `|| true` here because netlify has started returning 404's on success
            - (cd website && bolt deploy) || true

  default:
    - step:
        script:
          - source ./build-setup.sh
          - bolt install
          - bolt build
          - bolt lint
          - bolt typecheck
          - bolt test
          - bolt test:browser:browserstack
          # disabled until we figure out why netlify is returning 500's
          # - (cd website && bolt deploy-staging) || true
