image: node:8.4.0
pipelines:
  branches:
    master:
      - step:
          script:
            - source ./build-setup.sh
            - pyarn install
            - yarn build
            - yarn lint
            - yarn test
            - yarn release

  default:
    - step:
        script:
          - echo "$PATH"
          - which yarn
          - source ./build-setup.sh
          - echo "$PATH"
          - which yarn
          - pyarn install
          - yarn build
          - yarn lint
          - yarn test
