image: node:8.4.0
pipelines:
  branches:
    master:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install
            - (cd build/ci-scripts && bolt stop-if-older-build)
            - bolt build
            - bolt lint
            - bolt typecheck
            - bolt test
            - bolt test:browser:browserstack
            - bolt release
            # we `|| true` here because netlify has started returning 404's on success
            - (cd website && bolt deploy)
            - (cd build/ci-scripts && bolt restart-stopped-build)

  default:
    - step:
        script:
          - source ./build-setup.sh
          - bolt install
          - bolt build
          - bolt lint
          - bolt typecheck
          - bolt test
          - bolt test:browser:browserstack
          - (cd website && bolt deploy-staging:no-minimize)
