image: node:8.4.0
pipelines:
  branches:
    master:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install
            - bolt build
            - bolt lint
            - bolt test
            - bolt release

  default:
    - step:
        script:
          - source ./build-setup.sh
          - bolt install
          - bolt build
          - bolt lint
          - bolt test
