image: node:8.4.0
pipelines:
  branches:
    master:
      - step:
          script:
            # Note: in master, this script will rebase you onto latest origin/master
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - (cd build/ci-scripts && bolt stop-if-older-build)
            - bolt build
            - bolt lint
            - bolt typecheck
            - bolt test:ci
            - bolt test:browser:browserstack
            - bolt release
            - (cd build/ci-scripts && bolt restart-stopped-build)

  default:
    - step:
        script:
          - source ./build-setup.sh
          - bolt delete
          - bolt install --pure-lockfile
          - bolt build
          - bolt lint
          - bolt typecheck
          - bolt test:ci
          - bolt test:browser:browserstack
          - (cd website && bolt deploy-staging:no-minimize)

  custom: # Pipelines that can be scheduled or triggered manually

    # This should only be called by a scheduled build
    build-website-production:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - (cd website && bolt deploy)
