image: node:8.4.0
pipelines:
  branches:
    master:
      - step:
          script:
            - ./build-setup.sh
            - pyarn install
            - yarn build
            - yarn lint
            - yarn test
            - yarn release
          caches:
            - node
  default:
    - step:
        script:
          - ./build-setup.sh
          - mkdir -p packages/build/changelog-md-loader/node_modules/.bin
          - pyarn install
          - yarn build
          - yarn lint
          - yarn test
          - yarn release
