# This document is used to track releases.
# It can be editted manually, but it is reccomended you use the `yarn run version` command.

# Hash of the last release from master
last-release = "12345678"

[[releases]]
release = "releases/darkmode.md"
commits = [
  "12345678",
]
versions = [
  "package-1@major",
]

[[releases]]
commits = [
  "12345678",
]
versions = [
  "package-1@major",
]

[[releases]]
commits = [
  "12345678",
  "12345678",
  "12345678"
]
versions = [
  "package-1@major",
  "package-2@minor",
  "package-3@patch",
]

[[releases]]
commits = [
  "12345678",
  "12345678",
  "12345678",
]
versions = [
  "package-1@major",
  "package-2@minor",
  "package-3@patch",
]
