export declare const LANGUAGE_MAP: {
    actionscript: string;
    applescript: string;
    'c++': string;
    coldfusion: string;
    csharp: string;
    css: string;
    delphi: string;
    diff: string;
    erlang: string;
    groovy: string;
    java: string;
    javafx: string;
    javascript: string;
    perl: string;
    php: string;
    plaintext: string;
    powershell: string;
    python: string;
    ruby: string;
    sass: string;
    scala: string;
    shell: string;
    sql: string;
    visualbasic: string;
    xml: string;
};
export declare type LanguageMapKeys = keyof typeof LANGUAGE_MAP;
export declare const supportedLanguages: string[];
export declare function mapCodeLanguage(language: LanguageMapKeys): string;
