export default {
  type: 'array',
  items: [
    [
      'paragraph_with_no_marks',
      'bulletList',
      'mediaSingle',
      'orderedList',
      'heading_with_no_marks',
      'panel',
      'blockquote',
      'rule',
      'table',
      'codeBlock_no_marks',
      'mediaGroup',
      'applicationCard',
      'decisionList',
      'taskList',
      'extension',
      'blockCard',
    ],
  ],
  minItems: 1,
  allowUnsupportedBlock: true,
};
