declare const _default: {
    'fabric.atlassianSwitcher.switchTo': string;
    'fabric.atlassianSwitcher.switchToTooltip': string;
    'fabric.atlassianSwitcher.recent': string;
    'fabric.atlassianSwitcher.more': string;
    'fabric.atlassianSwitcher.try': string;
    'fabric.atlassianSwitcher.manageList': string;
    'fabric.atlassianSwitcher.jiraProject': string;
    'fabric.atlassianSwitcher.confluenceSpace': string;
    'fabric.atlassianSwitcher.people': string;
    'fabric.atlassianSwitcher.administration': string;
    'fabric.atlassianSwitcher.discoverMore': string;
    'fabric.atlassianSwitcher.errorHeading': string;
    'fabric.atlassianSwitcher.errorText': string;
    'fabric.atlassianSwitcher.errorImageAltText': string;
};
/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
export default _default;
