export declare const akEditorCodeFontFamily: any;
export declare const akEditorInactiveForeground: string;
export declare const akEditorFocus: string;
export declare const akEditorSubtleAccent: string;
export declare const akEditorActiveBackground: string;
export declare const akEditorActiveForeground: string;
export declare const akEditorBlockquoteBorderColor: string;
export declare const akEditorDropdownActiveBackground: string;
export declare const akEditorPopupBackground: string;
export declare const akEditorPopupText: string;
export declare const akEditorPrimaryButton: string;
export declare const akEditorCodeBackground: string;
export declare const akEditorCodeBlockPadding = "12px";
export declare const akEditorCodeInlinePadding = "2px 4px";
export declare const akEditorUnitZIndex = 1;
export declare const akEditorSmallZIndex = 2;
export declare const akEditorGridLineZIndex = 9999;
export declare const akEditorMenuZIndex: any;
export declare const akEditorFloatingPanelZIndex: any;
export declare const akEditorFloatingDialogZIndex: any;
export declare const akEditorFloatingOverlapPanelZIndex: any;
export declare const akEditorMentionSelected: string;
export declare const akEditorTableToolbarSize = 11;
export declare const akEditorTableBorder: string;
export declare const akEditorTableBorderDark: string;
export declare const akEditorTableToolbar: string;
export declare const akEditorTableToolbarDark: string;
export declare const akEditorTableFloatingControls: string;
export declare const akEditorTableCellSelected: string;
export declare const akEditorTableToolbarSelected: string;
export declare const akEditorTableBorderSelected: string;
export declare const akEditorTableCellDelete: string;
export declare const akEditorTableBorderDelete: string;
export declare const akEditorTableToolbarDelete: string;
export declare const akEditorTableBorderRadius = "3px";
export declare const akEditorTableCellBackgroundOpacity = 0.5;
export declare const akEditorFullPageMaxWidth = 680;
export declare const akEditorDefaultLayoutWidth = 680;
export declare const akEditorWideLayoutWidth = 960;
export declare const akEditorFullWidthLayoutWidth = 1800;
export declare const akEditorTableNumberColumnWidth = 42;
export declare const akEditorBreakoutPadding = 96;
export declare const akEditorMobileBreakoutPoint = 720;
export declare const akEditorTableCellMinWidth = 48;
export declare const akEditorTableLegacyCellMinWidth = 128;
export declare const gridMediumMaxWidth = 1024;
export declare const breakoutWideScaleRatio = 1.33;
export declare type EditorTheme = {
    baseFontSize?: number;
};
export declare const editorFontSize: ({ theme }: {
    theme: EditorTheme;
}) => any;
export declare const relativeSize: (multiplier: number) => ({ theme, }: {
    theme: EditorTheme;
}) => number;
export declare const blockNodesVerticalMargin = 1.143;
