export declare const tableToolbarColor: string;
export declare const tableBorderColor: string;
export declare const tableFloatingControlsColor: string;
export declare const tableCellSelectedColor: string;
export declare const tableToolbarSelectedColor: string;
export declare const tableBorderSelectedColor: string;
export declare const tableCellDeleteColor: string;
export declare const tableBorderDeleteColor: string;
export declare const tableToolbarDeleteColor: string;
export declare const tableToolbarSize = 11;
export declare const tableBorderRadiusSize = 3;
export declare const tableInsertColumnButtonSize = 20;
export declare const tableDeleteButtonSize = 16;
export declare const tablePadding = 8;
export declare const contextualMenuTriggerSize = 16;
export declare const contextualMenuDropdownWidth = 180;
export declare const layoutButtonSize = 32;
export declare const tableInsertColumnButtonLeftOffset = 22;
export declare const tableInsertColumnButtonTopOffset = 22;
export declare const tableStyles: import("styled-components").InterpolationValue[];
export declare const tableFullPageEditorStyles: import("styled-components").InterpolationValue[];
export declare const tableCommentEditorStyles: import("styled-components").InterpolationValue[];
export declare const tablePopupStyles: import("styled-components").InterpolationValue[];
