import * as tslib_1 from "tslib";
import styled, { css } from 'styled-components';
import { colors, gridSize } from '@atlaskit/theme';
export var SearchBox = styled.div(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n  position: sticky;\n  top: 0;\n  z-index: 1; /* required to keep the search box on top of icons in results when sticky */\n  background-color: ", ";\n  color: ", ";\n  display: flex;\n  height: 36px;\n  padding-bottom: 2px;\n  border-bottom: 2px solid ", ";\n  z-index: 10;\n"], ["\n  position: sticky;\n  top: 0;\n  z-index: 1; /* required to keep the search box on top of icons in results when sticky */\n  background-color: ", ";\n  color: ", ";\n  display: flex;\n  height: 36px;\n  padding-bottom: 2px;\n  border-bottom: 2px solid ", ";\n  z-index: 10;\n"])), colors.N0, colors.N500, colors.B200);
export var SearchFieldBaseInner = styled.div(templateObject_2 || (templateObject_2 = tslib_1.__makeTemplateObject(["\n  padding-right: ", "px; /* pad search text from FieldBase's isLoading spinner */\n  display: flex;\n  flex-grow: 1;\n"], ["\n  padding-right: ",
    "px; /* pad search text from FieldBase's isLoading spinner */\n  display: flex;\n  flex-grow: 1;\n"])), gridSize() *
    2);
export var SearchInner = styled.div(templateObject_3 || (templateObject_3 = tslib_1.__makeTemplateObject(["\n  padding-right: ", "px;\n"], ["\n  padding-right: ", "px;\n"])), gridSize() * 3);
export var getPlaceholderStyle = function (style) { return css(templateObject_4 || (templateObject_4 = tslib_1.__makeTemplateObject(["\n  &::-webkit-input-placeholder {\n    ", ";\n  }\n  &::-moz-placeholder {\n    /* Mozilla Firefox 19+ */\n    ", " opacity: 1;\n  }\n  &::-ms-input-placeholder {\n    /* Microsoft Edge */\n    ", ";\n  }\n  &:-moz-placeholder {\n    /* Mozilla Firefox 4 to 18 */\n    ", " opacity: 1;\n  }\n  &:-ms-input-placeholder {\n    /* Internet Explorer 10-11 */\n    ", ";\n  }\n"], ["\n  &::-webkit-input-placeholder {\n    ", ";\n  }\n  &::-moz-placeholder {\n    /* Mozilla Firefox 19+ */\n    ", " opacity: 1;\n  }\n  &::-ms-input-placeholder {\n    /* Microsoft Edge */\n    ", ";\n  }\n  &:-moz-placeholder {\n    /* Mozilla Firefox 4 to 18 */\n    ", " opacity: 1;\n  }\n  &:-ms-input-placeholder {\n    /* Internet Explorer 10-11 */\n    ", ";\n  }\n"])), style, style, style, style, style); };
export var getPlaceholderColor = css(templateObject_5 || (templateObject_5 = tslib_1.__makeTemplateObject(["\n  color: ", ";\n"], ["\n  color: ", ";\n"])), colors.placeholderText);
export var SearchInput = styled.input(templateObject_6 || (templateObject_6 = tslib_1.__makeTemplateObject(["\n  background-color: ", ";\n  border: 0;\n  color: ", ";\n  flex-grow: 1;\n  font-size: 1.4em;\n  outline: 0;\n  ", ";\n"], ["\n  background-color: ", ";\n  border: 0;\n  color: ", ";\n  flex-grow: 1;\n  font-size: 1.4em;\n  outline: 0;\n  ", ";\n"])), colors.N0, colors.N500, getPlaceholderStyle(getPlaceholderColor));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6;
//# sourceMappingURL=styled.js.map