import * as tslib_1 from "tslib";
import styled from 'styled-components';
import { colors, typography } from '@atlaskit/theme';
import gridSizeTimes from '../../util/gridSizeTimes';
export var Screen = styled.div(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n  width: 640px;\n  margin-bottom: ", "px;\n  > p {\n    margin-top: ", "px;\n    margin-bottom: ", "px;\n  }\n"], ["\n  width: 640px;\n  margin-bottom: ", "px;\n  > p {\n    margin-top: ", "px;\n    margin-bottom: ", "px;\n  }\n"])), gridSizeTimes(2), gridSizeTimes(3), gridSizeTimes(2));
export var LoadingWrapper = styled.div(templateObject_2 || (templateObject_2 = tslib_1.__makeTemplateObject(["\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  height: 500px;\n"], ["\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  height: 500px;\n"])));
export var Title = styled.div(templateObject_3 || (templateObject_3 = tslib_1.__makeTemplateObject(["\n  ", ";\n  margin-bottom: ", "px;\n  margin-top: 0;\n"], ["\n  ", ";\n  margin-bottom: ", "px;\n  margin-top: 0;\n"])), typography.h700, gridSizeTimes(3));
export var SectionMessageOuter = styled.div(templateObject_4 || (templateObject_4 = tslib_1.__makeTemplateObject(["\n  margin: ", "px 0;\n"], ["\n  margin: ", "px 0;\n"])), gridSizeTimes(3));
export var MainInformationList = styled.ul(templateObject_5 || (templateObject_5 = tslib_1.__makeTemplateObject(["\n  > li {\n    margin-top: ", "px;\n    margin-left: ", "px;\n    padding-left: ", "px;\n    b {\n      font-weight: 600;\n    }\n  }\n  p + ul {\n    margin-top: ", "px;\n  }\n"], ["\n  > li {\n    margin-top: ", "px;\n    margin-left: ", "px;\n    padding-left: ", "px;\n    b {\n      font-weight: 600;\n    }\n  }\n  p + ul {\n    margin-top: ", "px;\n  }\n"])), gridSizeTimes(2), gridSizeTimes(1.5), gridSizeTimes(3), gridSizeTimes(1.5));
export var IconHoverWrapper = styled.span(templateObject_6 || (templateObject_6 = tslib_1.__makeTemplateObject(["\n  color: ", ";\n  &:hover {\n    color: ", ";\n  }\n"], ["\n  color: ", ";\n  &:hover {\n    color: ", ";\n  }\n"])), colors.B500, colors.B200);
export var InlineDialogContent = styled.div(templateObject_7 || (templateObject_7 = tslib_1.__makeTemplateObject(["\n  li {\n    margin-left: ", "px;\n    margin-top: ", "px;\n    padding-left: ", "px;\n  }\n"], ["\n  li {\n    margin-left: ", "px;\n    margin-top: ", "px;\n    padding-left: ", "px;\n  }\n"])), gridSizeTimes(3), gridSizeTimes(1), gridSizeTimes(1));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7;
//# sourceMappingURL=styled.js.map