export declare const selected = "emoji-common-selected";
export declare const selectOnHover = "emoji-common-select-on-hover";
export declare const emojiSprite = "emoji-common-emoji-sprite";
export declare const emojiNode = "emoji-common-node";
export declare const deleteButton: string;
export declare const emoji: string;
export declare const emojiContainer: string;
export declare const placeholder = "emoji-common-placeholder";
export declare const placeholderContainer: string;
export declare const placeholderEmoji: string;
export declare const emojiButton: string;
export declare const buttons = "emoji-common-buttons";
export declare const preview = "emoji-common-preview";
export declare const previewImg = "emoji-common-preview-image";
export declare const previewText = "emoji-common-preview-text";
export declare const name = "emoji-common-name";
export declare const shortName = "emoji-common-shortname";
export declare const previewSingleLine = "emoji-common-preview-single-line";
export declare const toneSelectorContainer = "emoji-common-tone-selector-container";
export declare const withToneSelector = "emoji-common-with-tone-selector";
export declare const emojiPreviewSection = "emoji-preview-section";
export declare const emojiPreview: string;
export declare const emojiScrollable: string;
export declare const emojiUpload: string;
export declare const uploadChooseFileMessage: string;
export declare const emojiUploadBottom: string;
export declare const uploadChooseFileRow: string;
export declare const uploadChooseFileEmojiName: string;
export declare const uploadChooseFileBrowse: string;
export declare const uploadPreviewFooter: string;
export declare const uploadPreview: string;
export declare const uploadPreviewText: string;
export declare const bigEmojiPreview: string;
export declare const uploadAddRow: string;
export declare const AddCustomEmoji: string;
export declare const submitDelete = "emoji-submit-delete";
export declare const previewButtonGroup = "emoji-preview-button-group";
export declare const deletePreview: string;
export declare const deleteText: string;
export declare const deleteFooter: string;
export declare const emojiDeleteErrorMessage: string;
export declare const emojiChooseFileErrorMessage: string;
export declare const emojiPreviewErrorMessage: string;
export declare const addCustomEmojiButton: string;
export declare const uploadRetryButton: string;
export declare const uploadEmojiButton: string;
export declare const cancelButton: string;
export declare const buttonSpinner: string;
